### ISSUE TITLE
app.missing() not working

### ISSUE THREAD

**Issue by Nosthertus** [bayorigin/diet#53]
Diet version: 0.10.7

`app.missing()` is not working when there is no uri that matches with the request

**Comment by adamhalasz** [comment]
Do you still get this on v.10.8?

**Comment by Nosthertus** [comment]
Not anymore. thanks for the fix, i was planning to work on it but i got really busy

**Comment by Nosthertus** [comment]
i just found another bug on the missing method. which i know a workaround for this, but just in case you keep it in mind..

This bug happens again when footer is called and does not call `$.return()`

**Comment by Nosthertus** [comment]
Looks like this bug is back again on version `0.10.8`

**Comment by Nosthertus** [comment]
nevermind.. it was a proxy problem
