### ISSUE TITLE
Nginx doesn't work with Diet?

### ISSUE THREAD

**Issue by rudimk** [bayorigin/diet#55]
I have a Diet.js API running on ```http://127.0.0.1:6000```, and I'm trying to set up nginx to proxy requests to the API. But it doesn't work - nginx invariably throws up a ```404 host not found``` error.

I saw [this](https://github.com/adamhalasz/diet/issues/16) issue, and it seems similar to the predicament I'm in. Unfortunately, I can't figure out where to apply the same fix, because I suppose ```models/host.js``` was deprecated or something. How can I get this to work?

Thanks!

**EDIT** - I've also tried running the API on ```0.0.0.0```, but the same problem persists.

**Comment by rudimk** [comment]
Okay, so I dug around a bit and found [#29](https://github.com/adamhalasz/diet/issues/29). I tried setting ```app.listen('http://PUBLIC_IP:6000')``` but that gives the same error.

**Comment by adamhalasz** [comment]
Hey @rudimk if you see the `404 host not found` error that means Diet responded. I think the problem is somewhere with the `host` that nginx forwards to Diet.

Please can you add the below snippet right after you create a Server Instance and then run your app and open `http://127.0.0.1:6000`. I would like to see the logs from that.
```
app.onAny(function(value){
    var path = value && value.route ? 'path='+value.route.path : '' ;
    
    if(path.indexOf('function') != -1){
        var path = value && value.method ? 'method='+value.method : 'method="unknown"'; 
    }
    
    var controller = value && value.controller ? 'controller='+value.controller : '' ;
    var url = value && value.signal && value.signal.url ? 'url="'+value.signal.url.href+'"' : '' ;
    
    console.log(' ... APP', url, 'event="' + this.event + '"', path, controller)
})  
```

Also can you please show me your nginx configuration?

**Comment by rudimk** [comment]
Okay, so I added the snippet, and tried to open a route:
```
... APP  event="listen"
 ... HTTP Server is listening on http://104.215.139.49:6000/
 ... APP  event="route.attach" path=/v1/:product_id/business-units
 ... APP  event="route.attach" path=/v1/:product_id/states
 ... APP  event="route.attach" path=/v1/:product_id/:business_unit_id/:state_id/residents
 ... APP  event="route.start"
 ... APP  event="route.start"
```

And, here's my nginx configuration:

```
server {
    listen 80;

    server_name api.dartboardiq.com;

    access_log  /var/log/nginx/uprising_access.log;
    error_log  /var/log/nginx/uprising_error.log;

    location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_pass http://104.215.139.49:6000/;
    }
}
```

**Comment by adamhalasz** [comment]
@rudimk sorry I updated my answer. Please can you run it with the updated code?

**Comment by rudimk** [comment]
Okay, so here's what happens now. Accessing the API through 127.0.0.1:6000 on my server gives me this, which is pretty valid for my use case:
```
.. APP  event="listen"
 ... HTTP Server is listening on http://127.0.0.1:6000/
 ... APP  event="route.attach" path=/v1/:product_id/business-units
 ... APP  event="route.attach" path=/v1/:product_id/states
 ... APP  event="route.attach" path=/v1/:product_id/:business_unit_id/:state_id/residents
 ... APP  event="route.start"
 ... APP url="/v1/1/business-units" event="route.headers"
 ... APP url="/v1/1/business-units" event="route.body"
 ... APP url="/v1/1/business-units" event="route.start" path=/v1/:product_id/business-units
 ... APP url="/v1/1/business-units" event="route.controller.start" path=/v1/:product_id/business-units controller=/v1/:product_id/business-units
 ... APP url="/v1/1/business-units" event="route.controller.skip" path=/v1/:product_id/business-units controller=/v1/:product_id/business-units
 ... APP url="/v1/1/business-units" event="route.controller.start" path=/v1/:product_id/business-units controller=function ($){
	var flag
	checkAuth($, flag, function($, flag){
		if (flag) {
			var product_id = parseInt($.params.product_id, 10)
			connection.query('SELECT id as business_unit_id, business_unit_name FROM business_unit WHERE product_id = ? ORDER BY id', [product_id],
		function(err, rows, fields) {
			if (err) throw err
			console.log(rows)
			$.json(rows)
		})
		}
		else {
			$.json({error: 'Your auth token is invalid.'})
		}
	})
}
0
 ... APP  event="route.footer"
```

Now if I try accessing it from outside - through a request on my Mac, it returns the 404 host not found, and the log looks like this:

```
... APP  event="listen"
 ... HTTP Server is listening on http://127.0.0.1:6000/
 ... APP  event="route.attach" path=/v1/:product_id/business-units
 ... APP  event="route.attach" path=/v1/:product_id/states
 ... APP  event="route.attach" path=/v1/:product_id/:business_unit_id/:state_id/residents
 ... APP  event="route.start"
```

**Comment by rudimk** [comment]
Also, I'm sure my code isn't exactly too optimized. Javascript's still feels new.

**Comment by rudimk** [comment]
Damn, I missed the other questions.
- Nginx stands at v1.4.6
- Node's at v0.12.15
- Diet's at v0.10.8
- I'm running Ubuntu 14.04 on Azure.

**Comment by adamhalasz** [comment]
@rudimk sorry for the late reply. Thanks for the environment details. Diet had some issues before with pre-configured cloud environments, it may be related. Have you tried this with a local nginx or a vps like digitalocean? 

In my latest code snippet there is a second console log which logs the signal "...... APP -> Signal". The signal has a much more information like the header which includes the host. Please can you show me an output result with the signal? 

Thanks,
Adam

**Comment by rudimk** [comment]
Hey, not at all!

> "Diet had some issues before with pre-configured cloud environments, it may be related."
Bit confused about what pre-configured means here. I mean, I've installed everything here, no orchestration whatsoever. Also, I haven't done this on a local system or on DO, but I can try that too.

So here's the log when I hit an API route in my app:
```
... APP  event="listen"
...... APP -> Signal:  undefined
 ... HTTP Server is listening on http://127.0.0.1:6000/

... APP  event="route.attach" path=/v1/:product_id/business-units
...... APP -> Signal:  undefined

... APP  event="route.attach" path=/v1/:product_id/states
...... APP -> Signal:  undefined

... APP  event="route.attach" path=/v1/:product_id/:business_unit_id/:state_id/residents
...... APP -> Signal:  undefined

... APP  event="route.start"
...... APP -> Signal:  undefined
```

**Comment by rudimk** [comment]
I'm also planning to spin up a basic proxy using http-proxy - got the idea from your response on [#56](https://github.com/adamhalasz/diet/issues/56).

**Comment by rudimk** [comment]
I spun up a very basic http proxy. Same results - 404 host not found. If I then redirect that proxy to a basic Express app, it works just fine. Here's a dump of the proxy code, if it's of any help:

```
var http = require('http'),
      httpProxy = require('http-proxy'),
      HttpProxyRules = require('http-proxy-rules');

var proxyRules = new HttpProxyRules({
        rules: {
                'api.dartboardiq.com': 'http://localhost:6000'
                },
        default: 'http://localhost:6000'
        });


var proxy = httpProxy.createProxy();

http.createServer(function(req, res) {

        var target = proxyRules.match(req);
    if (target) {
      return proxy.web(req, res, {
        target: target
      });
    }

res.writeHead(500, { 'Content-Type': 'text/plain' });
    res.end('The request url and path did not match any of the listed rules!');
  }).listen(80);
```

**Comment by rudimk** [comment]
Hey @adamhalasz! Hate to bug you, but do you have any pointers on this thread? For now, I'm probably going to run the API server on port 80 without nginx, but ideally that's not a situation one would want to continue with, especially when we need to start load-balancing.

**Comment by adamhalasz** [comment]
hey @rudimk sorry for the late reply I'm really busy this week. I will look into this over the weekend/beginning of next week.

**Comment by rudimk** [comment]
No problem! For now, the API's running pretty well without any proxy. Thanks for the help! Do let me know if I can be of any help when you get back to this :)

**Comment by adamhalasz** [comment]
hey @rudimk thanks for your patience. I'm really tied up in my own work but I'm going to work on this as soon as I can, when I will have some more time on my hands. We're going to use nginx as well at my company. I'm going to deal with this pretty soon. 

How is diet performing without nginx by the way? If you don't mind me asking, what are you working on?

Thanks,
Adam

**Comment by rudimk** [comment]
Hey, no problem! I can understand. The thing is, it's not just nginx - even using node-http-proxy throws the same error. Not sure if this is something to do with the way I've written my code, or it's something to do with Diet. But yeah, I suppose we'll figure it out.

Diet works just fine without nginx. The drawback is that I can't exactly run anything else on the server, since port 80 is blocked for Diet's use. But that's fine. I'm working on a transactional analytics engine, and we wanted to build a dev API for our clients to plug their tools into - so for instance, they could use our API to get a list of all users in a particular cohort and then take that list and send a newsetter campaign, stuff like that.

**Comment by rudimk** [comment]
Hello! Any news on this issue?

**Comment by adamhalasz** [comment]
hey @rudimk 

I'm really sorry for the late answer. I've been busy with my company and moving. 

I think I just found the issue. You are specifying the `host` header as `$host` which will be `api.dartboardiq.com` but diet is listening on `http://127.0.0.1:6000/`. This is why you are getting a host not found error. 

This nginx configuration works for me on Localhost. Let me know if it works for you as well:
```conf
server {
    listen 80;

    server_name localhost;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host 0.0.0.0:3000;
        proxy_cache_bypass $http_upgrade;
    }
}
```
This redirects `http://localhost/` (nginx) to `http://0.0.0.0:3000/` (node.js). As you can see I'm setting the `proxy_set_header Host` directive to `0.0.0.0:3000` to do that.

Let me know if this works for you and if you have any questions.

Kind Regards,
Adam

**Comment by rudimk** [comment]
Hey Adam!

First off, congratulations on the company setup! I noticed Diet's repo ownership changed. Sounds pretty cool!

Second - it worked like a charm! It didn't strike me that the `$host` in the nginx config needed to be changed to match the host and port Diet ran on. Makes perfect sense. Thanks ever so much! 

PS - [A small attempt](https://medium.com/p/koa-diet-js-i-fd6e1e42d151) at spreading my new-found love for Diet.

**Comment by adamhalasz** [comment]
Hey @rudimk,

I'm really glad it works for you! Again sorry for the late answer! Thanks a lot for your patience. I just finished reading your article, it's amazing! 

Sincerely,
Adam
