### ISSUE TITLE
Semantic-ui and RekordJs Support or Module?

### ISSUE THREAD

**Issue by topcheese** [bayorigin/diet#57]
I'm not that great at coding, but I was thinking of using the three together. I'm going to try and hopefully hack something together, but it would be nice if there was some sort of official support to help start me off.
~Thanks!

**Comment by topcheese** [comment]
I'm not that great at coding, but I was thinking of using the three together.  I'm going to try and hopefully hack something together, but it would be nice if there was some sort of official support to help start me off.
~Thanks!

**Comment by adamhalasz** [comment]
Hey @topcheese I'm glad you would like to use diet! I don't have experience with Semantic-ui and RekordJS, so I can't tell you specifics. I'm pretty sure you can make the 3 work together 😉 

Have a look at [diet-vue](https://github.com/adamhalasz/diet-vue). [Vue.js](http://vuejs.org/) is a Reactive Library. It could give you some inspiration on how to connect the Frontend and the Backend in a dynamic way. 
[https://github.com/adamhalasz/diet-vue](https://github.com/adamhalasz/diet-vue)

As for support, Diet will soon have official support from [BayOrigin](http://bayorigin.com/). In the meantime, let me know if you have any specific questions.

You can reach me here on [GitHub](https://github.com/adamhalasz/diet), [StackOverflow](https://stackoverflow.com/users/380562/adam) or shoot me an [Email](adam@bayorigin.com)

Thanks,
Adam
