### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by ahmadibrahim-c** [bayorigin/diet#66]
This framework is really great but the website says the current version is 0.9 while here it is 0.10, the last commit and issues are like 4 months old..

So I wonder if this framework is still maintained

**Comment by adamhalasz** [comment]
Hey @ahmadibrahim-c yes it is maintained, I'm just very busy working on my startup recently.

**Comment by ahmadibrahim-c** [comment]
Good to know, wish you luck @adamhalasz
